services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: ros-lms-db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-container
    hostname: dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    working_dir: /home/dynamodblocal
    volumes:
      - dynamodb-data:/home/dynamodblocal
    healthcheck:
      test: [ "CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/8000" ]
      interval: 5s
      timeout: 5s
      retries: 5

  dynamodb-setup:
    image: amazon/aws-cli:latest
    container_name: dynamodb-setup
    depends_on:
      dynamodb:
        condition: service_started
    environment:
      AWS_ACCESS_KEY_ID: fakeMyKeyId
      AWS_SECRET_ACCESS_KEY: fakeSecretAccessKey
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - ./init-dynamodb.sh:/init-dynamodb.sh
    entrypoint: [ "/bin/sh", "/init-dynamodb.sh" ]
    profiles:
      - dynamodb-setup
    restart: "no"

volumes:
  mysql-data:
  dynamodb-data: