-- Create database
CREATE DATABASE IF NOT EXISTS `ros-lms-db`;
USE `ros-lms-db`;

-- Drop tables if they exist (in reverse order of creation due to FK constraints)
DROP TABLE IF EXISTS LOANS;
DROP TABLE IF EXISTS LOAN_STATUSES;
DROP TABLE IF EXISTS STAFFS;
DROP TABLE IF EXISTS MEMBERS;
DROP TABLE IF EXISTS USERS_AUTHORITIES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS BOOKS_GENRES;
DROP TABLE IF EXISTS BOOKS_AUTHORS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRE_TYPE;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS AUTHORITY_TYPE;
DROP PROCEDURE IF EXISTS GENERATE_LOG;

-- Create tables with named constraints
CREATE TABLE GENRE_TYPE (
    GENRE_ID BIGINT AUTO_INCREMENT,
    LABEL VARCHAR(50),
    CONSTRAINT GENRE_ID_PK PRIMARY KEY (GENRE_ID),
    CONSTRAINT GENRE_LABEL_UK UNIQUE (LABEL)
);

CREATE TABLE BOOKS (
    BOOK_ID BIGINT AUTO_INCREMENT,
    ISBN VARCHAR(13),
    TITLE VARCHAR(50) NOT NULL,
    IS_AVAILABLE CHAR(1),
    COVER_IMAGE_PATH VARCHAR(200),
    CREATED_AT DATETIME DEFAULT NULL,
    UPDATED_AT DATETIME DEFAULT NULL,
    CONSTRAINT BOOK_ID_PK PRIMARY KEY (BOOK_ID),
    CONSTRAINT BOOK_ISBN_UK UNIQUE (ISBN),
    CONSTRAINT BOOK_AVAILABLE_CK CHECK (IS_AVAILABLE IN ('Y', 'N'))
);

CREATE TABLE BOOKS_GENRES (
    BOOK_ID BIGINT,
    GENRE_ID BIGINT,
    CONSTRAINT BOOKGENRE_PK PRIMARY KEY (BOOK_ID, GENRE_ID),
    CONSTRAINT BOOKGENRE_BOOK_FK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
    CONSTRAINT BOOKGENRE_GENRE_FK FOREIGN KEY (GENRE_ID) REFERENCES GENRE_TYPE(GENRE_ID)
);

CREATE TABLE AUTHORS (
    AUTHOR_ID BIGINT AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    MIDDLE_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT AUTHOR_ID_PK PRIMARY KEY (AUTHOR_ID),
    CONSTRAINT AUTHOR_NAME_UK UNIQUE (FIRST_NAME, MIDDLE_NAME, LAST_NAME)
);

CREATE TABLE BOOKS_AUTHORS (
    BOOK_ID BIGINT,
    AUTHOR_ID BIGINT,
    CONSTRAINT BOOKAUTHOR_PK PRIMARY KEY (BOOK_ID, AUTHOR_ID),
    CONSTRAINT BOOKAUTHOR_BOOK_FK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
    CONSTRAINT BOOKAUTHOR_AUTHOR_FK FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

CREATE TABLE AUTHORITY_TYPE (
    AUTHORITY_TYPE_ID INT AUTO_INCREMENT,
    LABEL VARCHAR(128),
    CONSTRAINT AUTHORITY_TYPE_ID_PK PRIMARY KEY (AUTHORITY_TYPE_ID),
    CONSTRAINT AUTHORITY_TYPE_LABEL_UK UNIQUE (LABEL)
);

CREATE TABLE USERS (
    USER_ID BIGINT AUTO_INCREMENT,
    USERNAME VARCHAR(128),
    EMAIL VARCHAR(128),
    PASSWORD VARCHAR(128) NOT NULL,
    ENABLED CHAR(1) NOT NULL,
    CONSTRAINT USER_ID_PK PRIMARY KEY (USER_ID),
    CONSTRAINT USER_NAME_UK UNIQUE (USERNAME),
    CONSTRAINT USER_EMAIL_UK UNIQUE (EMAIL),
    CONSTRAINT USER_ENABLED_CK CHECK (ENABLED IN ('Y','N'))
);

CREATE TABLE USERS_AUTHORITIES (
    USER_ID BIGINT NOT NULL,
    AUTHORITY_TYPE_ID INT NOT NULL,
    CONSTRAINT USERS_AUTHORITIES_PK PRIMARY KEY (USER_ID, AUTHORITY_TYPE_ID),
    CONSTRAINT USERS_AUTHORITIES_USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT USERS_AUTHORITIES_AUTHORITY_FK FOREIGN KEY (AUTHORITY_TYPE_ID) REFERENCES AUTHORITY_TYPE (AUTHORITY_TYPE_ID)
);

CREATE TABLE MEMBERS (
    MEMBER_ID BIGINT AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    GOVERNMENT_ID VARCHAR(15),
    FIRST_NAME VARCHAR(50) NOT NULL,
    MIDDLE_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    DATE_OF_BIRTH DATE,
    SEX CHAR(1),
    CREATED_AT DATETIME DEFAULT NULL,
    UPDATED_AT DATETIME DEFAULT NULL,
    CONSTRAINT MEMBER_ID_PK PRIMARY KEY (MEMBER_ID),
    CONSTRAINT MEMBER_GOV_ID_UK UNIQUE (GOVERNMENT_ID),
    CONSTRAINT MEMBER_SEX_CK CHECK (SEX IN ('M', 'F')),
    CONSTRAINT MEMBER_USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT MEMBER_USER_UK UNIQUE (USER_ID)
);

CREATE TABLE STAFFS (
    STAFF_ID BIGINT AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    GOVERNMENT_ID VARCHAR(15),
    FIRST_NAME VARCHAR(50) NOT NULL,
    MIDDLE_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    SEX CHAR(1),
    CREATED_AT DATETIME DEFAULT NULL,
    UPDATED_AT DATETIME DEFAULT NULL,
    CONSTRAINT STAFF_ID_PK PRIMARY KEY (STAFF_ID),
    CONSTRAINT STAFF_GOV_ID_UK UNIQUE (GOVERNMENT_ID),
    CONSTRAINT STAFF_SEX_CK CHECK (SEX IN ('M', 'F')),
    CONSTRAINT STAFF_USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT STAFF_USER_UK UNIQUE (USER_ID)
);

CREATE TABLE LOAN_STATUSES (
    STATUS_ID BIGINT AUTO_INCREMENT,
    CODE VARCHAR(50),
    CONSTRAINT LOAN_STATUS_ID_PK PRIMARY KEY (STATUS_ID),
    CONSTRAINT LOAN_STATUS_CODE_UK UNIQUE (CODE)
);

CREATE TABLE LOANS (
    LOAN_ID BIGINT AUTO_INCREMENT,
    MEMBER_ID BIGINT,
    BOOK_ID BIGINT,
    LOAN_DATE DATETIME NOT NULL,
    DUE_DATE DATETIME NOT NULL,
    RETURN_DATE DATETIME,
    STATUS_ID BIGINT,
    STAFF_ID BIGINT,
    CREATED_AT DATETIME DEFAULT NULL,
    UPDATED_AT DATETIME DEFAULT NULL,
    CONSTRAINT LOAN_ID_PK PRIMARY KEY (LOAN_ID),
    CONSTRAINT LOAN_MEMBER_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
    CONSTRAINT LOAN_BOOK_FK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
    CONSTRAINT LOAN_STATUS_FK FOREIGN KEY (STATUS_ID) REFERENCES LOAN_STATUSES(STATUS_ID),
    CONSTRAINT LOAN_STAFF_ID FOREIGN KEY (STAFF_ID) REFERENCES STAFFS(STAFF_ID)
);

-- Speeds up WHERE TITLE LIKE '%...%'
CREATE INDEX idx_books_title ON BOOKS (TITLE);

-- Helps JOIN and WHERE g.description LIKE '%...%'
CREATE INDEX idx_genres_label ON GENRE_TYPE (LABEL);

-- These assist with filtering by name parts individually.
CREATE INDEX idx_authors_first_name ON AUTHORS (FIRST_NAME);
CREATE INDEX idx_authors_middle_name ON AUTHORS (MIDDLE_NAME);
CREATE INDEX idx_authors_last_name ON AUTHORS (LAST_NAME);

-- Helps with JOIN BOOKS_GENRES -> GENRES.
CREATE INDEX idx_books_genres_genre_id ON BOOKS_GENRES (GENRE_ID);

-- Helps with JOIN BOOKS_AUTHORS -> AUTHORS.
CREATE INDEX idx_books_authors_author_id ON BOOKS_AUTHORS (AUTHOR_ID);

-- Speeds up the View MEMBER_STATUS_VIEW
CREATE INDEX idx_loans_status_member ON LOANS (STATUS_ID, MEMBER_ID);

-- Insert Authority Types
INSERT INTO AUTHORITY_TYPE (LABEL) VALUES
('ROLE_ADMIN'),
('ROLE_STAFF'),
('ROLE_MEMBER');

-- Insert Users with clearer role-based usernames
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED, EMAIL) VALUES
('admin',  '$2a$10$S.g6r.ug0CAHKEyPnV5KEu.PCSjh01/xcduj5Ufntpk567lOUI0/a', 'Y', 'admin@example.com'),
('member', '$2a$10$S.g6r.ug0CAHKEyPnV5KEu.PCSjh01/xcduj5Ufntpk567lOUI0/a', 'Y', 'member@example.com'),
('staff',  '$2a$10$S.g6r.ug0CAHKEyPnV5KEu.PCSjh01/xcduj5Ufntpk567lOUI0/a', 'Y', 'staff@example.com');


-- Assign Appropriate Roles
INSERT INTO USERS_AUTHORITIES (USER_ID, AUTHORITY_TYPE_ID)
VALUES
(1,  (SELECT AUTHORITY_TYPE_ID FROM AUTHORITY_TYPE WHERE LABEL = 'ROLE_ADMIN')),
(1,  (SELECT AUTHORITY_TYPE_ID FROM AUTHORITY_TYPE WHERE LABEL = 'ROLE_STAFF')),
(1,  (SELECT AUTHORITY_TYPE_ID FROM AUTHORITY_TYPE WHERE LABEL = 'ROLE_MEMBER')),
(3,  (SELECT AUTHORITY_TYPE_ID FROM AUTHORITY_TYPE WHERE LABEL = 'ROLE_STAFF')),
(3,  (SELECT AUTHORITY_TYPE_ID FROM AUTHORITY_TYPE WHERE LABEL = 'ROLE_MEMBER')),
(2, (SELECT AUTHORITY_TYPE_ID FROM AUTHORITY_TYPE WHERE LABEL = 'ROLE_MEMBER'));

-- Insert Members
INSERT INTO MEMBERS (
    USER_ID, GOVERNMENT_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME,
    PHONE, DATE_OF_BIRTH, SEX
) VALUES (
    (SELECT USER_ID FROM USERS WHERE USERNAME = 'member'),
    'M123456789', 'Jane', 'K.', 'Doe',
    '123-456-7890', '1990-05-10', 'F'
);

-- Insert Staffs
INSERT INTO STAFFS (
    USER_ID, GOVERNMENT_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME,
    PHONE, SEX
) VALUES (
    (SELECT USER_ID FROM USERS WHERE USERNAME = 'staff'),
    'M123456755', 'John', NULL, 'Admin',
    '321-654-0987', 'M'
);

INSERT INTO STAFFS (
    USER_ID, GOVERNMENT_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME,
    PHONE, SEX
) VALUES (
    (SELECT USER_ID FROM USERS WHERE USERNAME = 'admin'),
    '40200402747', 'Carlos', 'Alexander', 'Rosario Sanchez',
    '6474256438', 'M'
);

-- Insert initial genre data
INSERT INTO GENRE_TYPE (LABEL) VALUES ('MYSTERY');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('SCIENCE FICTION');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('ROMANCE');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('FANTASY');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('THRILLER');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('HISTORICAL FICTION');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('HORROR');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('BIOGRAPHY');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('SELF-HELP');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('ADVENTURE');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('CHILDREN LITERATURE');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('NON-FICTION');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('GRAPHIC NOVEL');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('POETRY');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('DYSTOPIAN');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('CRIME');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('AUTOBIOGRAPHY');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('ESSAYS');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('PHILOSOPHY');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('RELIGION');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('SCIENCE');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('ART');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('COOKING');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('TRAVEL');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('SPORTS');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('TECHNOLOGY');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('DRAMA');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('POLITICAL FICTION');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('LANGUAGE');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('HISTORY');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('MAGAZINE');
INSERT INTO GENRE_TYPE (LABEL) VALUES ('FICTION');

INSERT INTO LOAN_STATUSES (CODE) VALUES
('LOANED'),
('RETURNED'),
('OVERDUE'),
('RETURNED-LATE'),
('LOST');

CREATE OR REPLACE VIEW MEMBER_STATUS_VIEW AS
SELECT
    m.MEMBER_ID,
    m.FIRST_NAME,
    m.LAST_NAME,
    CASE
        WHEN EXISTS (
            SELECT 1
            FROM LOANS l
            WHERE l.MEMBER_ID = m.MEMBER_ID AND l.STATUS_ID = 3 -- OVERDUE
        ) THEN 'OVERDUE'

        WHEN EXISTS (
            SELECT 1
            FROM LOANS l
            WHERE l.MEMBER_ID = m.MEMBER_ID AND l.STATUS_ID = 1 -- LOANED
        ) THEN 'HAS-LOAN'

        ELSE 'ELIGIBLE'
    END AS MEMBER_STATUS
FROM MEMBERS m;


-- Insert Dummy Authors
INSERT INTO AUTHORS (FIRST_NAME, MIDDLE_NAME, LAST_NAME) VALUES
('John', 'A.', 'Smith'),
('Alice', NULL, 'Walker'),
('Robert', 'B.', 'Johnson'),
('Emily', NULL, 'Davis'),
('Michael', NULL, 'Brown'),
('Laura', 'C.', 'Miller'),
('David', NULL, 'Wilson'),
('Sarah', 'E.', 'Taylor'),
('James', NULL, 'Anderson'),
('Olivia', 'F.', 'Thomas');

-- Insert Dummy Books
INSERT INTO BOOKS (ISBN, TITLE, IS_AVAILABLE, COVER_IMAGE_PATH) VALUES
('9780000000001', 'The Lost Artifact', 'Y', NULL),
('9780000000002', 'Echoes of Tomorrow', 'Y', NULL),
('9780000000003', 'Whispers in the Wind', 'Y', NULL),
('9780000000004', 'The Final Countdown', 'N', NULL),
('9780000000005', 'Hearts in Harmony', 'Y', NULL),
('9780000000006', 'Beyond the Stars', 'Y', NULL),
('9780000000007', 'Shadows of Deceit', 'N', NULL),
('9780000000008', 'Chronicles of the Unknown', 'Y', NULL),
('9780000000009', 'Mystic River', 'Y', NULL),
('9780000000010', 'Garden of Dreams', 'Y', NULL);


-- Map Books to Authors
INSERT INTO BOOKS_AUTHORS (BOOK_ID, AUTHOR_ID) VALUES
(1, 1), (1, 2),
(2, 3),
(3, 4), (3, 5),
(4, 6),
(5, 7), (5, 8),
(6, 9),
(7, 10), (7, 1),
(8, 2),
(9, 3), (9, 4),
(10, 5);


-- Map Books to Genres
-- We'll use GENRE_IDs assuming they were inserted in order
INSERT INTO BOOKS_GENRES (BOOK_ID, GENRE_ID) VALUES
(1, 1), (1, 10),         -- Mystery, Adventure
(2, 2),                  -- Science Fiction
(3, 3), (3, 5),          -- Romance, Thriller
(4, 4),                  -- Fantasy
(5, 6), (5, 14),         -- Historical Fiction, Poetry
(6, 2), (6, 21),         -- Science Fiction, Science
(7, 15), (7, 16),        -- Dystopian, Crime
(8, 13),                 -- Graphic Novel
(9, 1), (9, 7),          -- Mystery, Horror
(10, 3), (10, 11);       -- Romance, Children's Literature